In [1]:
from __future__ import print_function
import torch

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[9.2755e-39, 1.0561e-38, 1.0469e-38],
        [9.6429e-39, 9.2755e-39, 4.2246e-39],
        [1.0286e-38, 1.0653e-38, 1.0194e-38],
        [8.4490e-39, 1.0469e-38, 9.3674e-39],
        [9.9184e-39, 8.7245e-39, 9.2755e-39]])


In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.9946, 0.1559, 0.6096],
        [0.6653, 0.8558, 0.1451],
        [0.9133, 0.7023, 0.1770],
        [0.5847, 0.8044, 0.4271],
        [0.9728, 0.3415, 0.1915]])


In [4]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.1730,  0.1084, -0.4954],
        [-1.4234,  0.8990, -0.0371],
        [-1.8700, -0.5477,  1.0596],
        [ 0.2449, -0.5873, -1.7694],
        [ 0.6389,  2.3776,  1.4882]])


In [5]:
print(x.size())

torch.Size([5, 3])


In [6]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([[ 0.8270,  1.1084,  0.5046],
        [-0.4234,  1.8990,  0.9629],
        [-0.8700,  0.4523,  2.0596],
        [ 1.2449,  0.4127, -0.7694],
        [ 1.6389,  3.3776,  2.4882]], device='cuda:0')
tensor([[ 0.8270,  1.1084,  0.5046],
        [-0.4234,  1.8990,  0.9629],
        [-0.8700,  0.4523,  2.0596],
        [ 1.2449,  0.4127, -0.7694],
        [ 1.6389,  3.3776,  2.4882]], dtype=torch.float64)


In [22]:
x=torch.ones(3,3,requires_grad=True)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)


In [23]:
y=x+2
print(y)

tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]], grad_fn=<AddBackward0>)


In [24]:
print(y.grad_fn)

In [25]:
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[27., 27., 27.],
        [27., 27., 27.],
        [27., 27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [26]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


In [27]:
out.backward()

In [28]:
print(x.grad)

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])


In [29]:
x = torch.randn(3, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2

print(y)

tensor([-257.4070, -433.2090, 1026.1211], grad_fn=<MulBackward0>)


In [30]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)

print(x.grad)

tensor([5.1200e+01, 5.1200e+02, 5.1200e-02])


In [31]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False


In [32]:
print(x.requires_grad)
y = x.detach()
print(y.requires_grad)
print(x.eq(y).all())

True
False
tensor(True)
